### ISSUE TITLE
sorting alphabetically, questions

### ISSUE THREAD

**Issue by jduss4** [CDRH/api#29]
Right now ES returns results like this:

`?facet_sort=alpha|desc`

```
{
  alice : 20,
  charlemagne: 30,
  Abigail : 20
}
```

Is it possible to sort alphabetically without regard to capitalization?
Also, is it possible to specify (maybe by field) whether empty values should go at the beginning or end of sorting alphabetically?

**Comment by jduss4** [comment]
@techgique may have a lead on this, I believe he looked into analyzers dealing with capitalization, etc

**Comment by karindalziel** [comment]
Another related issue to this is letters with diacritics sorting to the end (see family letters)

**Comment by karindalziel** [comment]
I believe this is don, diacritics might be another issue
