### ISSUE TITLE
Term matching with special characters

### ISSUE THREAD

**Issue by jduss4** [CDRH/api#67]
It seems likely that some facetable keyword fields may end up with special characters, like ampersands.  Right now these do not work via orchid.  Test if this is a problem with orchid's URL encoding, or if it has more to do with the API itself not currently supporting those strings.

Not certain that this will be required by Cather for launch, but will affect "Quills & Feathers" collection, for example.  I would assume that some works titles could have special characters, also

Related to closed issue https://github.com/CDRH/api/issues/23

**Comment by techgique** [comment]
Confident this has been fixed here: https://github.com/CDRH/orchid/commit/aab7a82bce3e12f3edbf8ff660e93287b698acb1#diff-6afeafbfc523a81fe237405f2bfa4e52L122
