### ISSUE TITLE
Indicate version in repo rather than config file

### ISSUE THREAD

**Issue by jduss4** [CDRH/api#76]

**Comment by jduss4** [comment]
This is a great idea, past Jessica.  See #88 for further need of it!  But where would we want to put it?

**Comment by techgique** [comment]
I think VERSION.md is not uncommon at the root of projects :man_shrugging:

**Comment by techgique** [comment]
Once I started reviewing the Datura PR, I noticed that the template documentation noted a `version.rb`

I know we wanted the version number available to access via Ruby for other repos, so perhaps we should do similar here.

**Comment by jduss4** [comment]
I vote that we figure out the version issue before we make a new release of the API

**Comment by jduss4** [comment]
It looks as though this has already been done!
