### ISSUE TITLE
Sort for browse page: case and unicode insensitive

### ISSUE THREAD

**Issue by karindalziel** [CDRH/api#96]
![Screen Shot 2019-09-06 at 10 21 09 AM](https://user-images.githubusercontent.com/284315/64439656-148a8080-d090-11e9-958c-38f5377c1235.png)

When we sort browse pages, it is case and unicode sensitive. 

Ideally, we could make it sort so any diacritics sort with the ascii character that most closely matches (so ñ would be sorted with "N" etc)

I have a feeling someone has solved this already. I found a few posts about the case insensitivity. i.e. https://www.technetexperts.com/web/case-insensitive-sorting-in-elasticsearch/ (not the nest post, just an example)

**Comment by jduss4** [comment]
Related to #29

**Comment by jduss4** [comment]
Use this for ascii conversions:
https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-asciifolding-tokenfilter.html

**Comment by jduss4** [comment]
The custom analyzer they show as their example does basically exactly what we want it to do, although I'd have to read up on the character filter.

https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-custom-analyzer.html

**Comment by jduss4** [comment]
Ah so I misled myself a little, the analyzers are NOT applicable to keyword fields, but it looks like they have normalizers instead:  https://www.elastic.co/guide/en/elasticsearch/reference/current/normalizer.html
