### ISSUE TITLE
Ability to search partial words using an asterisk appears not to be working

### ISSUE THREAD

**Issue by karindalziel** [CDRH/api#98]
As an example, if you search for sibe* in the cather search it should bring up results that contain her middle name, sibert

`https://cather-dev.unl.edu/search?utf8=%E2%9C%93&q=sibe*`

vs

`https://cather-dev.unl.edu/search?utf8=%E2%9C%93&q=sibert`

**Comment by jduss4** [comment]
See https://www.elastic.co/guide/en/elasticsearch/reference/6.7/query-dsl-query-string-query.html
